services:
  - type: web
    name: spms-1
    runtime: docker
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FORCE_REDEPLOY
        value: "2"
      - key: PORT
        value: "10000"
